apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointments-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointments
  template:
    metadata:
      labels:
        app: appointments
    spec:
      containers:
        - name: appointments
          image: saman1/appointments-img:latest
          ports:
            - containerPort: 6060
          env:
            - name: MONGO_URI
              value: "mongodb://mongodb:27017/Appointments"
---
apiVersion: v1
kind: Service
metadata:
  name: appointments-service
spec:
  selector:
    app: appointments
  ports:
    - protocol: TCP
      port: 80
      targetPort: 6060

