apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointments-deploy  # Corrected Deployment name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointments
  template:
    metadata:
      labels:
        app: appointments
    spec:
      containers:
      - name: appointments
        image: saman1/appointments-img:18
        ports:
        - containerPort: 6060
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: appointment
              key: mongo-uri
        - name: MONGO_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: appointment-config
              key: MONGO_DB_NAME  # Corrected ConfigMap name
        - name: NAME
          valueFrom:
            secretKeyRef:
              name: appointment
              key: NAME
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: appointment-secret
              key: PASSWORD
        readinessProbe:
          failureThreshold: 4
          httpGet:
            path: /health
            port: 6060
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 6060
          initialDelaySeconds: 20
          failureThreshold: 2
          periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: appointments-service
spec:
  selector:
    app: appointments
  ports:
    - protocol: TCP
      port: 6060
      targetPort: 6060
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: appointment-config  # Corrected ConfigMap name
data:
  MONGO_DB_NAME: "Appointments"

---
apiVersion: v1
kind: Secret
metadata:
  name: appointment-secret
data:
  mongo-uri: cmVhbGx5X21vbmdvLXVyaTovL3JlbGFseV9tLW9uZ28tc2VydmljZToyNzAxMA==
  NAME: YW1UYQ==
  PASSWORD: bXlfcGFzc3dvcmQ6MTIzNDU2

