apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: saman1/frontend-img:latest
          ports:
            - containerPort: 3000
          env:
            - name: DOCTORS_SERVICE_URL
              value: "doctors-service:9090"
            - name: APPOINTMENTS_SERVICE_URL
              value: "appointments-service:6060"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

