apiVersion: apps/v1
kind: Deployment
metadata:
  name: "front-deploy"
  namespace: frontend-microservice
  labels:
    app: "front-deploy"
spec:
  selector:
    matchLabels:
      app: "front-deploy"
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "front-deploy"
    spec:
      containers:
      - name: "front-deploy"
        image: saman1/frontend-img
        ports:
        - containerPort: 3000
          name: "front-deploy"
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 3
          failureThreshold: 2
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health2
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 1

---
apiVersion: v1
kind: Service
metadata:
  name: "frontend-service"
  namespace: frontend-microservice
spec:
  selector:
    app: "front-deploy"
  type: NodePort
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: "frontend-service"
    port: 30
    targetPort: 3000
