apiVersion: apps/v1
kind: Deployment
metadata:
  name: "db-deploy"
  namespace: db-microservice
  labels:
    app: "db-deploy"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "db-deploy"
  template:
    metadata:
      labels:
        app: "db-deploy"
    spec:
      containers:
      - name: "db-deploy"
        image: mongo:4.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017
          name: "db-deploy"
        livenessProbe:
          httpGet:
            path: /health
            port: 27017
          initialDelaySeconds: 3
          failureThreshold: 2
          periodSeconds: 3
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health2
            port: 27017
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 500m

---
apiVersion: v1
kind: Service
metadata:
  name: "db-service"
  namespace: db-microservice
spec:
  selector:
    app: "db-deploy"
  type: NodePort
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: "db-service"
    port: 27
    targetPort: 27017

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: db-deploy
  namespace: db-microservice
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: db-deploy
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50

