apiVersion: apps/v1
kind: Deployment
metadata:
  name: "doc-deploy"
  namespace: doctors-microservice
  labels:
    app: "doc-deploy"
spec:
  selector:
    matchLabels:
      app: "doc-deploy"
  replicas: 2
  template:
    metadata:
      labels:
        app: "doc-deploy"
    spec:
      containers:
      - name: "doc-deploy"
        image: saman1/doctors-img
        ports:
        - containerPort: 9090
          name: "doc-deploy"
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 9090
          initialDelaySeconds: 3
          failureThreshold: 2
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health2
            port: 9090
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 1

---
apiVersion: v1
kind: Service
metadata:
  name: "doctors-service"
  namespace: doctors-microservice
spec:
  selector:
    app: "doc-deploy"
  type: NodePort
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: "doctors-service"
    port: 90
    targetPort: 9090
  - name: "http-requests"
    port: 9090

