apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctors-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doctors
  template:
    metadata:
      labels:
        app: doctors
    spec:
      containers:
        - name: doctors
          image: saman1/doctors-img:latest
          ports:
            - containerPort: 9090
          env:
            - name: MONGO_URI
              value: "mongodb://mongodb:27017/DevOps"
---
apiVersion: v1
kind: Service
metadata:
  name: doctors-service
spec:
  selector:
    app: doctors
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090

