apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctors-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doctors
  template:
    metadata:
      labels:
        app: doctors
    spec:
      containers:
      - name: doctors
        image: saman1/doctors-img
        ports:
        - containerPort: 9090
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        env:
        - name: cpu
          value: "500m"
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: doctors-secret
              key: mongo-uri
        - name: MONGO_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: doctors-configMap
              key: MONGO_DB_NAME
        readinessProbe:
          failureThreshold: 4
          httpGet:
            path: /health
            port: 9090

---
apiVersion: v1
kind: Service
metadata:
  name: doctors-service
spec:
  selector:
    app: doctors
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: doctors-configMap
data:
  MONGO_DB_NAME: "DevOps"
---
apiVersion: v1 
kind: Secret 
metadata:
name: doctors-secret
type: Opaque
data:
mongo-uri: eXRvdWd2YmtfL21vbmdvLXNlcnZpY2U6MjcwMTc=

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: doctors
data:
  details.txt: |
    I am Saman Saeed.
    Currently pursuing software engineering from NUCES.
    I enjoy learning DevOps.
