name: CI/CD Pipeline

on:
  pull_request:
    paths:
      - "appointments/**"
      - "doctors/**"
      - "frontend/**"
  push:
    paths:
      - "appointments/**"
      - "doctors/**"
      - "frontend/**"
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Determine service folder
        id: service
        run: |
          BASE_FOLDER=$(find . -name Dockerfile -exec dirname {} \;)
          echo "Base Folder: $BASE_FOLDER"
          echo "BASE_FOLDER=$BASE_FOLDER" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            DOCKER_TAG="pr-${{ github.event.number }}-${{ github.sha }}"
          else
            DOCKER_TAG="${{ github.sha }}"
          fi

          docker build -t saman1/${BASE_FOLDER}-img:$DOCKER_TAG ./${BASE_FOLDER}
          docker push saman1/${BASE_FOLDER}-img:$DOCKER_TAG

      - name: Update Docker Compose file
        run: |
          cd ${{ github.workspace }}
          sed -i "s|saman1/${BASE_FOLDER}-img:.*|saman1/${BASE_FOLDER}-img:$DOCKER_TAG|" docker-compose.yaml

      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code || echo "Changes found"

      - name: Commit and push changes
        if: steps.git-check.outputs.return-value == 'Changes found'
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add docker-compose.yaml
          git commit -m "Update ${{ BASE_FOLDER }} microservice image tag to $DOCKER_TAG"
          git push origin main
